
export const FooterData = [
  {
    key:'Popular',
    label: '인기',
    path: '/destinations/Popular',
    list: [
      { city: '댈러스', desc: '장기 숙소', path: '/dallas-tx/stays/monthly' },
      { city: '갤버스턴', desc: '독채 숙소', path: '/galveston-tx/stays/houses' },

      { city: '포틀랜드', desc: '콘도 숙소', path: '/portland-or/stays/condos' },
      { city: '미니애폴리스', desc: '독채 숙소', path: '/minneapolis-mn/stays/houses' },

      { city: '클리블랜드', desc: '독채 숙소', path: '/cleveland-oh/stays/houses' },
      { city: '바르셀로나', desc: '저택 숙소', path: '/barcelona-spain/stays/villas' },

      { city: '카우아이카운티', desc: '콘도 숙소', path: '/kauai-hi/stays/condos' },
      { city: '휘슬러', desc: '장기 숙소', path: '/whistler-canada/stays/monthly' },

      { city: '걸프 쇼어스', desc: '휴가지 숙소', path: '/gulf-shores-al/stays' },
      { city: '오아후', desc: '휴가지 숙소', path: '/oahu-hi/stays' },

      { city: '교토시', desc: '아파트 숙소', path: '/kyoto-japan/stays/apartments' },
      { city: '오사카', desc: '아파트 숙소', path: '/osaka-japan/stays/apartments' },

      { city: '도쿄', desc: '독채 숙소', path: '/tokyo-japan/stays/houses' },
      { city: '후쿠오카', desc: '아파트 숙소', path: '/fukuoka-japan/stays/apartments' },

      { city: '파리', desc: '아파트 숙소', path: '/paris-fr/stays/apartments' },
      { city: '런던', desc: '독채 숙소', path: '/london-uk/stays/houses' },

      { city: '로마', desc: '휴가지 숙소', path: '/rome-it/stays' },
      { city: '밀라노', desc: '콘도 숙소', path: '/milan-it/stays/condos' },

      { city: '뉴욕', desc: '아파트 숙소', path: '/new-york-ny/stays/apartments' },
      { city: '로스앤젤레스', desc: '독채 숙소', path: '/los-angeles-ca/stays/houses' },

      { city: '샌프란시스코', desc: '콘도 숙소', path: '/san-francisco-ca/stays/condos' },
      { city: '시애틀', desc: '독채 숙소', path: '/seattle-wa/stays/houses' },

      { city: '밴쿠버', desc: '아파트 숙소', path: '/vancouver-canada/stays/apartments' },
      { city: '토론토', desc: '콘도 숙소', path: '/toronto-canada/stays/condos' },

      { city: '방콕', desc: '아파트 숙소', path: '/bangkok-th/stays/apartments' },
      { city: '치앙마이', desc: '휴가지 숙소', path: '/chiang-mai-th/stays' },

      { city: '두바이', desc: '저택 숙소', path: '/dubai-uae/stays/villas' },
      { city: '아부다비', desc: '휴가지 숙소', path: '/abu-dhabi-uae/stays' }
    ]},
  {
    key:'ArtCulture',
    label: '예술 및 문화',
    path: '/destinations/ArtCulture',
    list: [
      { city: '카멜백로지 & 인도어워터파크', desc: '통나무집 숙소', path: '/camelback-resort-tannersville-pa/stays/cabins' },
      { city: '잭 프로스트 스키 리조트', desc: '휴가지 숙소', path: '/jack-frost-ski-resort-white-haven-pa/stays' },
      { city: '파리', desc: '저택 숙소', path: '/paris-france/stays/villas' },
      { city: '애서티그섬', desc: '콘도 숙소', path: '/assateague-island/stays/condos' },
      { city: '노스캐스케이드 국립공원', desc: '휴가지 숙소', path: '/north-cascades-national-park-wa/stays' },
      { city: '아말피 해안', desc: '저택 숙소', path: '/amalfi-coast-italy/stays/villas' },
      { city: '포트레로 해변(코스타리카)', desc: '콘도 숙소', path: '/playa-potrero-costa-rica/stays/condos' },

      { city: '그레고리 호수', desc: '휴가지 숙소', path: '/lake-gregory-ca/stays' },
      { city: '코모 호', desc: '콘도 숙소', path: '/lake-como-italy/stays/condos' },
      { city: '로즈볼스태디엄', desc: '휴가지 숙소', path: '/rose-bowl-stadium-pasadena-ca/stays' },
      { city: '스노버드 스키 리조트 헬리포트', desc: '콘도 숙소', path: '/snowbird-ut/stays/condos' },
      { city: '코로나도 제도', desc: '저택 숙소', path: '/coronado-island-ca/stays/villas' },
      { city: '산타테레사', desc: '독채 숙소', path: '/santa-teresa-costa-rica/stays/houses' },
      { city: '더갤러리아', desc: '독채 숙소', path: '/the-galleria-houston-tx/stays/houses' },

      { city: '그랜비 랜치', desc: '아파트 숙소', path: '/granby-ranch-co/stays/apartments' },
      { city: '올림픽 국립공원', desc: '독채 숙소', path: '/olympic-national-park-port-angeles-wa/stays/houses' },
      { city: 'SoFi Stadium', desc: '독채 숙소', path: '/sofi-stadium-inglewood-ca/stays/houses' },
      { city: '노스스타 앳 타호 리조트', desc: '아파트 숙소', path: '/northstar-california-resort-truckee-ca/stays/apartments' },
      { city: '슈바이처 마운틴 리조트', desc: '콘도 숙소', path: '/schweitzer-sandpoint-id/stays/condos' },
      { city: '해운대 바닷가', desc: '아파트 숙소', path: '/haeundae-beach-south-korea/stays/apartments' },

      { city: '쿠야호가밸리 국립공원', desc: '휴가지 숙소', path: '/cuyahoga-valley-national-park-oh/stays' },
      { city: '타임스퀘어', desc: '독채 숙소', path: '/times-square-new-york-ny/stays/houses' },
      { city: '벨레이어 스키 센터', desc: '독채 숙소', path: '/belleayre-mountain-ski-center-shandaken-ny/stays/houses' },
      { city: '라스크로바스', desc: '독채 숙소', path: '/las-croabas-puerto-rico/stays/houses' },
      { city: '카멜백 마운틴 리조트', desc: '휴가지 숙소', path: '/camelback-ski-resort-tannersville-pa/stays' },

      { city: '내셔널하버', desc: '휴가지 숙소', path: '/national-harbor-md/stays' },
      { city: '홀리데이 밸리 스키 리조트', desc: '독채 숙소', path: '/holiday-valley-resort-ellicottville-ny/stays/houses' },
      { city: '피닉스 컨벤션 센터', desc: '휴가지 숙소', path: '/phoenix-convention-center-az/stays' },
      { city: 'Everglades', desc: '별장 숙소', path: '/everglades-fl/stays/cottages' },
      { city: '커크우드 마운틴 리조트', desc: '휴가지 숙소', path: '/kirkwood-mountain-resort-ca/stays' },

      { city: '사마라 비치', desc: '독채 숙소', path: '/samara-beach-costa-rica/stays/houses' },
      { city: '마사 비니야드', desc: '휴가지 숙소', path: '/marthas-vineyard-ma/stays' },
      { city: 'Sugarbush Resort', desc: '아파트 숙소', path: '/sugarbush-resort-warren-vt/stays/apartments' },
      { city: '비치 마운틴 스키 리조트', desc: '콘도 숙소', path: '/beech-mountain-ski-resort-nc/stays/condos' },
      { city: '세리토스 비치', desc: '아파트 숙소', path: '/cerritos-beach-mexico/stays/apartments' }
    ]},
  {
    key:'Beach',
    label: '해변',
    path: '/destinations/Beach',
    list: [
      { city: '로사리토 비치', desc: '장기 숙소', path: '/rosarito-beach-mexico/stays/monthly' },
      { city: '노스캐롤라이나주 라이츠빌 비치', desc: '콘도 숙소', path: '/wrightsville-beach-nc-wrightsville-beach-nc/stays/condos' },
      { city: '발리 사누르', desc: '저택 숙소', path: '/sanur-indonesia/stays/villas' },
      { city: '브리지타운', desc: '독채 숙소', path: '/bridgetown-barbados/stays/houses' },
      { city: '사율리타 비치', desc: '장기 숙소', path: '/playa-sayulita-mexico/stays/monthly' },
      { city: '플라야 노르테', desc: '아파트 숙소', path: '/playa-norte-isla-mujeres-mexico/stays/apartments' },
      { city: '루키요 비치', desc: '독채 숙소', path: '/luquillo-beach-puerto-rico/stays/houses' },
      { city: '갤버스턴 비치', desc: '휴가지 숙소', path: '/galveston-beach-tx/stays' },
      { city: '하날레이 베이', desc: '아파트 숙소', path: '/hanalei-bay-hi/stays/apartments' },
      { city: '카보산루카스', desc: '독채 숙소', path: '/cabo-san-lucas-mexico/stays/houses' },
      { city: '소수아 비치', desc: '장기 숙소', path: '/sosua-beach-dominican-republic/stays/monthly' },
      { city: '코클레스 비치', desc: '반려동물 동반 숙소', path: '/playa-cocles-costa-rica/stays/pet-friendly' },
      { city: '푼타 루시아', desc: '장기 숙소', path: '/punta-rucia-dominican-republic/stays/monthly' },
      { city: '피파 비치', desc: '장기 숙소', path: '/tibau-do-sul-brazil/stays/monthly' },
      { city: '콕센홀', desc: '저택 숙소', path: '/coxen-hole-honduras/stays/villas' },
      { city: '애나 마리아', desc: '콘도 숙소', path: '/anna-maria-fl/stays/condos' },
      { city: '코수멜', desc: '장기 숙소', path: '/san-miguel-de-cozumel-mexico/stays/monthly' },
      { city: '부예 해변', desc: '해변 바로 앞 숙소', path: '/buye-beach-cabo-rojo-puerto-rico/stays/beachfront' },
      { city: '푸푸케아', desc: '해변 바로 앞 숙소', path: '/pupukea-hi/stays/beachfront' },
      { city: '암파샤오 도스 부지오스', desc: '독채 숙소', path: '/armacao-dos-buzios-brazil/stays/houses' },
      { city: '카예 카울커', desc: '휴가지 숙소', path: '/caye-caulker-belize/stays' },
      { city: '파타야 비치', desc: '콘도 숙소', path: '/pattaya-beach-thailand/stays/condos' },
      { city: '빙긴 해변', desc: '저택 숙소', path: '/bingin-beach-indonesia/stays/villas' },
      { city: '새러소타 비치', desc: '아파트 숙소', path: '/sarasota-beach-fl/stays/apartments' },
      { city: '버라와 비치', desc: '저택 숙소', path: '/berawa-beach-kecamatan-kuta-utara-indonesia/stays/villas' },
      { city: '와이키키 비치', desc: '콘도 숙소', path: '/waikiki-beach-honolulu-hi/stays/condos' },
      { city: '퍼시픽 비치', desc: '콘도 숙소', path: '/pacific-beach-ca/stays/condos' },
      { city: '네그릴 세븐마일 비치', desc: '휴가지 숙소', path: '/negril-seven-mile-beach-jamaica/stays' }
    ]},
  {
    key:'Mountain',
    label: '산맥',
    path: '/destinations/Mountain',
    list: [
      { city: '화이트피쉬', desc: '아파트 숙소', path: '/whitefish-mt/stays/apartments' },
      { city: '버크아이', desc: '독채 숙소', path: '/buckeye-az/stays/houses' },
      { city: '웨인즈빌', desc: '아파트 숙소', path: '/waynesville-nc/stays/apartments' },
      { city: '피전포지', desc: '독채 숙소', path: '/pigeon-forge-tn/stays/houses' },
      { city: '팰로앨토', desc: '콘도 숙소', path: '/palo-alto-ca/stays/condos' },
      { city: '투손', desc: '장기 숙소', path: '/tucson-az/stays/monthly' },
      { city: '아이다호스프링스', desc: '독채 숙소', path: '/idaho-springs-co/stays/houses' },

      { city: '샌버너디노', desc: '통나무집 숙소', path: '/san-bernardino-ca/stays/cabins' },
      { city: '오자르크', desc: '통나무집 숙소', path: '/ozark-mo/stays/cabins' },
      { city: '산마테오', desc: '반려동물 동반 숙소', path: '/san-mateo-ca/stays/pet-friendly' },
      { city: '벤턴빌', desc: '통나무집 숙소', path: '/bentonville-ar/stays/cabins' },
      { city: '맨스최이스', desc: '아파트 숙소', path: '/cheyenne-wy/stays/apartments' },
      { city: '프레더릭스버그', desc: '콘도 숙소', path: '/fredericksburg-tx/stays/condos' },
      { city: '우리벨라레', desc: '반려동물 동반 숙소', path: '/mesa-az/stays/pet-friendly' },
      { city: '레드로지', desc: '아파트 숙소', path: '/red-lodge-mt/stays/apartments' },
      { city: '캘리스펠', desc: '콘도 숙소', path: '/kalispell-mt/stays/condos' },
      { city: '서니베일', desc: '장기 숙소', path: '/sunnyvale-ca/stays/monthly' },
      { city: '카슨시티', desc: '반려동물 동반 숙소', path: '/carson-city-nv/stays/pet-friendly' },
      { city: '듀랭고', desc: '반려동물 동반 숙소', path: '/durango-co/stays/pet-friendly' },
      { city: '오그던', desc: '독채 숙소', path: '/ogden-ut/stays/houses' },
      { city: '레드빌', desc: '독채 숙소', path: '/leadville-co/stays/houses' },
      { city: '볼더', desc: '반려동물 동반 숙소', path: '/boulder-co/stays/pet-friendly' },
      { city: '오더빌', desc: '장기 숙소', path: '/orderville-ut/stays/monthly' },
      { city: '해리슨버그', desc: '아파트 숙소', path: '/harrisonburg-va/stays/apartments' },
      { city: '코디', desc: '장기 숙소', path: '/cody-wy/stays/monthly' },
      { city: '브레바드', desc: '통나무집 숙소', path: '/brevard-nc/stays/cabins' },
      { city: '장크트모리츠', desc: '독채 숙소', path: '/saint-moritz-switzerland/stays/houses' },
      { city: '몽-트랑블랑', desc: '콘도 숙소', path: '/mont-tremblant-canada/stays/condos' },
      { city: '에구존-샨톰', desc: '독채 숙소', path: '/clovis-ca/stays/houses' },
      { city: '덴버', desc: '반려동물 동반 숙소', path: '/denver-co/stays/pet-friendly' },
      { city: '파예트빌', desc: '장기 숙소', path: '/fayetteville-ar/stays/monthly' },
      { city: 'Rio Rancho', desc: '반려동물 동반 숙소', path: '/rio-rancho-nm/stays/pet-friendly' },
      { city: '풀러턴', desc: '독채 숙소', path: '/fullerton-ca/stays/houses' },
      { city: '브리스톨', desc: '휴가지 숙소', path: '/bristol-tn/stays' },
      { city: '시스터스', desc: '휴가지 숙소', path: '/sisters-or/stays' },
      { city: '로즈빌', desc: '독채 숙소', path: '/roseville-ca/stays/houses' },
      { city: '비세일리아', desc: '독채 숙소', path: '/visalia-ca/stays/houses' },
      { city: '빌링스', desc: '아파트 숙소', path: '/billings-mt/stays/apartments' },
      { city: '시더시티', desc: '아파트 숙소', path: '/cedar-city-ut/stays/apartments' },
      { city: '리노', desc: '반려동물 동반 숙소', path: '/reno-nv/stays/pet-friendly' },
      { city: '아이언우드', desc: '반려동물 동반 숙소', path: '/ironwood-mi/stays/pet-friendly' },
      { city: '산페드로가르자가르시아', desc: '반려동물 동반 숙소', path: '/san-pedro-garza-garcia-mexico/stays/pet-friendly' },
      { city: '맥콜', desc: '반려동물 동반 숙소', path: '/mccall-id/stays/pet-friendly' },
      { city: '아파치정크션', desc: '장기 숙소', path: '/apache-junction-az/stays/monthly' },
      { city: '알파레타', desc: '장기 숙소', path: '/alpharetta-ga/stays/monthly' },
      { city: '과테말라시티', desc: '아파트 숙소', path: '/guatemala-city/stays/apartments' },
      { city: '글렌우드 스프링스', desc: '콘도 숙소', path: '/glenwood-springs-co/stays/condos' },
      { city: '윌리엄스', desc: '통나무집 숙소', path: '/williams-az/stays/cabins' }
    ]},
  {
    key:'Outdoor',
    label: '야외',
    path: '/destinations/Outdoor',
    list: [
      { city: '그린델발트', desc: '저택 숙소', path: '/grindelwald-switzerland/stays/villas' },
      { city: '데이나포인트', desc: '휴가지 숙소', path: '/dana-point-ca/stays' },
      { city: '나이아가라 폭포', desc: '해변 바로 앞 숙소', path: '/niagara-falls-canada/stays/beachfront' },
      { city: '스토', desc: '통나무집 숙소', path: '/stowe-vt/stays/cabins' },
      { city: '매머드레이크스', desc: '독채 숙소', path: '/mammoth-lakes-ca/stays/houses' },
      { city: '메드퍼드', desc: '독채 숙소', path: '/medford-or/stays/houses' },
      { city: '엘니도', desc: '해변 바로 앞 숙소', path: '/el-nido-philippines/stays/beachfront' },

      { city: 'Banff', desc: '콘도 숙소', path: '/banff-canada/stays/condos' },
      { city: 'Tacoma', desc: '독채 숙소', path: '/tacoma-wa/stays/houses' },
      { city: '피닉스', desc: '콘도 숙소', path: '/phoenix-az/stays/condos' },
      { city: '낙소스', desc: '콘도 숙소', path: '/naxos-greece/stays/condos' },
      { city: '모로베이', desc: '휴가지 숙소', path: '/morro-bay-ca/stays' },
      { city: '마라톤', desc: '별장 숙소', path: '/marathon-fl/stays/cottages' },
      { city: '도즈빌', desc: '해변 바로 앞 숙소', path: '/bradenton-beach-fl/stays/beachfront' },

      { city: '카롤리나', desc: '아파트 숙소', path: '/carolina-puerto-rico/stays/apartments' },
      { city: '하일랜즈', desc: '독채 숙소', path: '/highlands-nc/stays/houses' },
      { city: '푼타미타', desc: '저택 숙소', path: '/punta-mita-mexico/stays/villas' },
      { city: '조슈아 트리', desc: '저택 숙소', path: '/joshua-tree-ca/stays/villas' },
      { city: '오세이지비치', desc: '아파트 숙소', path: '/osage-beach-mo/stays/apartments' },
      { city: '케포스', desc: '아파트 숙소', path: '/quepos-costa-rica/stays/apartments' },
      { city: '누에보바야르타', desc: '아파트 숙소', path: '/nuevo-nayarit-mexico/stays/apartments' },

      { city: '타폰스프링스', desc: '독채 숙소', path: '/tarpon-springs-fl/stays/houses' },
      { city: '키라르고', desc: '휴가지 숙소', path: '/key-largo-fl/stays' },
      { city: '커내브', desc: '별장 숙소', path: '/kanab-ut/stays/cottages' },
      { city: '케이프타운', desc: '콘도 숙소', path: '/cape-town-south-africa/stays/condos' },
      { city: '프린스빌', desc: '휴가지 숙소', path: '/princeville-hi/stays' },
      { city: '알부페이라', desc: '저택 숙소', path: '/albufeira-portugal/stays/villas' },
      { city: '팜스프링스', desc: '별장 숙소', path: '/palm-springs-ca/stays/cottages' }
    ]},
  {
    key:'ThingsToDo',
    label: '즐길거리',
    path: '/destinations/ThingsToDo',
    list: [
      { city: '푸에블라', desc: '문화 예술', path: '/puebla-mexico/things-to-do/art-and-culture' },
      { city: '멕시코시티', desc: '문화 예술', path: '/mexico-city/things-to-do/art-and-culture' },
      { city: '더럼', desc: '스포츠 활동', path: '/durham-united-kingdom/things-to-do/sports' },
      { city: 'Apennine Mountains', desc: '문화 예술', path: '/apennine-mountains-italy/things-to-do/art-and-culture' },
      { city: '산후안', desc: '투어', path: '/san-juan-puerto-rico/things-to-do/tours' },
      { city: 'Honshu', desc: '자연 탐방 및 야외 활동', path: '/honshu-japan/things-to-do/nature-and-outdoors' },
      { city: '센 강', desc: '식도락', path: '/seine-france/things-to-do/food-and-drink' },
      { city: '파리', desc: '식도락', path: '/paris-france/things-to-do/food-and-drink' },
      { city: '도쿄', desc: '문화 예술', path: '/tokyo-japan/things-to-do/art-and-culture' },
      { city: 'Tama River', desc: '문화 예술', path: '/tama-river-japan/things-to-do/art-and-culture' },
      { city: '로마', desc: '즐길 거리', path: '/rome-italy/things-to-do' },
      { city: '메데인강', desc: '즐길 거리', path: '/medellin-river-colombia/things-to-do' },
      { city: '메데인', desc: '즐길 거리', path: '/medellin-colombia/things-to-do' },
      { city: '플레인뷰', desc: '웰니스', path: '/plainview-ny/things-to-do/wellness' },
      { city: 'Tokyo Bay', desc: '투어', path: '/tokyo-bay-japan/things-to-do/tours' },
      { city: '피렌체', desc: '엔터테인먼트', path: '/florence-italy/things-to-do/entertainment' },
      { city: '세미놀', desc: '자연 탐방 및 야외 활동', path: '/seminole-fl/things-to-do/nature-and-outdoors' },
      { city: '오악사카', desc: '관광', path: '/oaxaca-mexico/things-to-do/sightseeing' },
      { city: '시부야', desc: '스포츠 활동', path: '/shibuya-japan/things-to-do/sports' },
      { city: '바르셀로나', desc: '엔터테인먼트', path: '/barcelona-spain/things-to-do/entertainment' },
      { city: '서울', desc: '웰니스', path: '/seoul-south-korea/things-to-do/wellness' },
      { city: '뉴욕', desc: '즐길 거리', path: '/new-york-ny/things-to-do' },
      { city: '런던', desc: '투어', path: '/london-united-kingdom/things-to-do/tours' }
    ]}
];